package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"hitrix-crud/entity"
	"hitrix-crud/graph/model"

	"git.ice.global/packages/beeorm/v4"
	"git.ice.global/packages/hitrix/service"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {

	fmt.Println("========CreateUser1=======")

	orm := service.DI().OrmEngineForContext(ctx)

	fmt.Println("========CreateUser2=======")

	userEntity := &entity.User{
		Name: input.Name,
		Age:  int(input.Age),
	}

	fmt.Println("=======start Flush=======")

	orm.Flush(userEntity)

	fmt.Println("=======end Flush=======")

	return &model.User{}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	ormEngine := service.DI().OrmEngineForContext(ctx)

	// BeeORM-এর সাথে সব user লোড করার জন্য Search ব্যবহার করবো
	var userEntities []*entity.User
	ormEngine.Search(beeorm.NewWhere("1 = 1"), nil, &userEntities) // 1=1 মানে সব row

	// entity → GraphQL model-এ convert করবো
	var gqlUsers []*model.User
	for _, userEntity := range userEntities {
		gqlUsers = append(gqlUsers, &model.User{
			ID:   string(userEntity.ID), // gqlgen model-এ ID সাধারণত int বা string হয়
			Name: userEntity.Name,
			Age:  int32(userEntity.Age),
		})
	}

	return gqlUsers, nil
}
// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
